services:
  node-1:
    build: .
    command: ["__node", "6379", "node-1"]
    ports:
      - "6379:6379"

  node-2:
    build: .
    command: ["__node", "6379", "node-2"]
    ports:
      - "6380:6379"

  node-3:
    build: .
    command: ["__node", "6379", "node-3"]
    ports:
      - "6381:6379"
