services:
  redis-standalone:
    image: emberdb-redis-profiler:local
    build:
      context: .
      dockerfile: Dockerfile.redis-profiler
    ports: ["127.0.0.1::6060"]

  redis-1:
    image: emberdb-redis-profiler:local
    build:
      context: .
      dockerfile: Dockerfile.redis-profiler
    ports: ["127.0.0.1::6060"]

  redis-2:
    image: emberdb-redis-profiler:local
    build:
      context: .
      dockerfile: Dockerfile.redis-profiler
    ports: ["127.0.0.1::6060"]

  redis-3:
    image: emberdb-redis-profiler:local
    build:
      context: .
      dockerfile: Dockerfile.redis-profiler
    ports: ["127.0.0.1::6060"]

  bench-runner:
    image: emberdb-bench-profiler:local
    build:
      context: .
      dockerfile: Dockerfile.bench-profiler
