import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';

const { outputFiles } = await build({
  entryPoints: [new URL('./src/main.ts', import.meta.url).pathname],
  bundle: true, write: false, format: 'iife', target: ['es2022'], minify: true,
  legalComments: 'inline',
});
const template = await readFile(new URL('./index.html', import.meta.url), 'utf8');
const script = outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
await writeFile(new URL('../scripts/bench-dashboard.html', import.meta.url),
  '<!-- Generated by dashboard/build.mjs; edit dashboard/ sources. -->\n' +
  template.replace('<!-- dashboard-script -->', () => `<script>${script}</script>`));
console.log('Built scripts/bench-dashboard.html (self-contained, no runtime CDN).');
